
ZSH_THEME="random"
zsh_theme_random_candidates=( "robbyrussell"
    "afowler"
    "alanpeabody"
    "amuse"
    "apple"
    "arrow"
    "aussiegeek"
    "avit"
    "awesomepanda"
    "bira"
    "candy"
    "clean"
    "cloud"
    "crcandy"
    "crunch"
    "dallas"
    "dieter"
    "dpoggi"
    "dstufft"
    "duellj"
    "emotty"
    "essembeh"
    "fino-time"
    "fino"
    "flazz"
    "fletcherm"
    "gentoo"
    "gnzh"
    "half-life"
    "intheloop"
    "itchy"
    "jonathan"
    "kafeitu"
    "murilasso"
    "nanotech"
    "nebirhos"
    "obraun"
    "pygmalion"
    "rkj-repos"
    "strug"
    "wedisagree"
    "xiong-chiamiov"
    "agnoster" )
#distro tube 
colorscript random
